***SLIDE 11-16***;
PROC IMPORT FILE= "Z:\Dropbox\Didattica\Data\WARTS.XLSX"
OUT=WARTS  DBMS=XLSX REPLACE;
RUN;


PROC FREQ DATA=WARTS ;
TABLES CURED / BINOMIAL(P=0.4) ;
RUN;

PROC FREQ DATA=WARTS ;
TABLES CURED / BINOMIAL(P=0.4) ALPHA=0.1 ;
RUN;

***SLIDE 25***;
PROC IMPORT FILE= "Z:\Dropbox\Didattica\Data\ADGI.XLSX"
OUT=ADGI  DBMS=XLSX REPLACE;
RUN;

PROC FORMAT;
VALUE GRP 1="NUOVO ANTIBIOTICO" 2="ERITROMICINA" ;
VALUE GI 1="AE GI" 0="NO AE GI";
RUN;
PROC FREQ DATA=ADGI;
TABLES GRP*GI / NOCOL NOPERCENT;
FORMAT GI GI. GRP GRP.;
RUN;

***SLIDE 29***;
PROC FREQ DATA=ADGI;
TABLES GRP*GI / NOCOL NOPERCENT RISKDIFF;
FORMAT GI GI. GRP GRP.;
RUN;

***SLIDE 37***;
PROC FREQ DATA=ADGI;
TABLES GRP*GI / NOCOL NOPERCENT EXPECTED CHISQ;
FORMAT GI GI. GRP GRP.;
RUN;


***SLIDE 45***;
PROC IMPORT FILE= "Z:\Dropbox\Didattica\Data\DOSERESP.XLSX"
OUT=DOSERESP  DBMS=XLSX REPLACE;
RUN;
PROC FREQ DATA=DOSERESP;
TABLES DOSE_MG*TOXICITY / NOCOL NOPERCENT PLOTS=FREQPLOT;
RUN;

***SLIDE 51***;
PROC FREQ DATA=DOSERESP;
WHERE DOSE_MG IN (10,80);
TABLES DOSE_MG*TOXICITY / NOCOL NOPERCENT CHISQ;
RUN;

***SLIDE 55***;
PROC FREQ DATA=DOSERESP;
TABLES DOSE_MG*TOXICITY / NOCOL NOPERCENT TREND;
RUN;


***SLIDE 63***;

PROC IMPORT FILE= "Z:\Dropbox\Didattica\Data\BILI.XLSX"
OUT=BILI  DBMS=XLSX REPLACE;
RUN;
PROC FREQ DATA=BILI;
TABLES PRE*PST / NOCOL NOPERCENT NOROW;
RUN;

***SLIDE 64***;

PROC FREQ DATA=BILI;
TABLES PRE*PST / AGREE;
RUN;
